### ISSUE TITLE
Auswertung der Analyse und Tests zu Gelb/Rot-Status der Steps und des Builds

### ISSUE THREAD

**Issue by soenkekueper** [set-de/jenkins_ws#11]

**Comment by foto-andreas** [comment]
In JENKINS-26522 (Ticket ist in Progress) soll das Verhalten über das BlueOcean-Plugin gelöst werden. Der aktuelle Status ist wohl:
* teilweise implementiert
* nicht vollständig
* Plugins der statischen Code-Analyse nutzen es nicht.

Das API gibt die gleichen Infos aus, zur Zeit ist mit fehlgeschlagenem Findbugs (UNSTABLE) jeder Step in der Pipeline und die gesamte Pipeline unstable.

**Comment by foto-andreas** [comment]
Tests ergeben:

* Ein Step mit Returncode != 0 löst eine Exception aus. 
** Wird diese nicht gefangen, wird der Step rot und die Pipeline bricht ab.
** Wird diese gefangen, kann der Pipeline-Status gesetzt werden:
*** setzt man auf SUCCESS, ist Step grün und Pipeline bleibt grün
*** setzt man auf UNSTABLE, wird **jeder Step** in der Pipeline gelb, die Pipeline auch
*** setzt man auf FAILED, wird Pipeline ROT, Step bleibt grün, Pipeline läuft weiter
* Ein Plugin zur Statischen Code-Analayse setzt die Pipeline auf UNSTABLE und jeder Step wird gelb.

**Comment by foto-andreas** [comment]
Hi Andreas,

This is more or less correct.  We currently don't have a way to store the information needed to track UNSTABLE status down to the step level.  We have added a TagsAction which can be used to store this in the future (via JENKINS-26522) but are not yet reading or writing it for this purpose.

What remains is:

1. Add the status implementation using the TagsAction (in workflow-api plugin, probably) - trivial, a few hours of effort but doesn't do anything useful without the below.

2. Have pipeline steps (such as findbugs) set this action on their steps, and verify it is correctly reflected when the pipeline runs.  Complexity depends on how these are implemented, so it will vary.

3.  Look for this custom status override and use it when assigning statuses to steps & blocks of the pipeline.  This would take days of effort plus likely some smaller bugfixes (but not likely weeks).  This would be in pipeline graph analysis plugin and is surprisingly complex due to the number of cases it has to handle.   However, once done correctly this will be reflected in the stage view REST API, the stage view UI, and Blue Ocean. 

In order to release this as a feature, we need all 3 steps done with at least 1-2 reference implementations of 2.  I think #2 is something that could come from a community contribution but am hesitant to offer this up until it is clear when we'll have capacity to do #3.

I'm looping in our PM, Patrick on this, because he is the one best equipped to speak to priorities and schedules for delivery of pipeline features. 

Kindest regards (mit freundlichen Grüßen),
Sam Van Oort
